AWSTemplateFormatVersion: 2010-09-09
Description: cf-target-deploy
Parameters:
  OPSAccountId:
    Description: ID of the ops account
    Type: String
    Default: '201804844653'
Resources:
  CloudformationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ramazans-cloudformation-deployment-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${OPSAccountId}:root
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        #s3 access to ci/cd buckets
        - PolicyName: s3-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketPolicy
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::*-pipeline*
                  - arn:aws:s3:::*-template-config*
                  - arn:aws:s3:::*-nested-scripts*
          #kms access to ops account ci/cd encryption key
        - PolicyName: kms-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:DescribeKey
                  - kms:GenerateDataKey*
                  - kms:Encrypt
                  - kms:ReEncrypt*
                  - kms:Decrypt
                Resource:
                  - !Sub 'arn:aws:kms:*:${OPSAccountId}:key/*'
        #cloudformation
        - PolicyName: cloudformation-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource:
                  - !Sub arn:aws:cloudformation:*:${AWS::AccountId}:stack/*
                  - arn:aws:cloudformation:*:aws:transform/Serverless-2016-10-31
        #iam
        - PolicyName: iam-manage-roles
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRolePolicy
                  - iam:PutRolePolicy
                  - iam:DetachRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:Tag*
                  - iam:Untag*
                  - iam:UpdateAssumeRolePolicy
                  - iam:CreateServiceLinkedRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/*
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - arn:aws:iam::*:role/*
              - Effect: Allow
                Action:
                  - iam:CreateInstanceProfile
                  - iam:ListInstanceProfiles
                  - iam:GetInstanceProfile
                  - iam:AddRoleToInstanceProfile
                  - iam:DeleteInstanceProfile
                  - iam:RemoveRoleFromInstanceProfile
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/*
                  - !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/*
        #ec2
        - PolicyName: ec2-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*NetworkAcl*
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:DeleteRouteTable
                  - ec2:*VpcPeeringConnection
                  - ec2:CreateInternetGateway
                  - ec2:ReleaseAddress
                  - ec2:allocateAddress
                  - ec2:CreateVpc
                  - ec2:DeleteVpc
                  - ec2:ModifyVpcAttribute
                  - ec2:CreateRouteTable
                  - ec2:AssociateRouteTable
                  - ec2:DisassociateRouteTable
                  - ec2:ReplaceRouteTableAssociation
                  - ec2:CreateTags
                  - ec2:CreateSubnet
                  - ec2:DeleteSubnet
                  - ec2:ModifySubnetAttribute
                  - ec2:CreateSecurityGroup
                  - ec2:AttachInternetGateway
                  - ec2:DetachInternetGateway
                  - ec2:CreateNatGateway
                  - ec2:DeleteNatGateway
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:RunInstances
                  - ec2:CreateRoute
                  - ec2:DeleteRoute
                  - ec2:DeleteRouteTable
                  - ec2:Describe*
                  - ec2:Get*
                  - ec2:deleteTags
                  - ec2:CreateVolume
                  - ec2:ModifyVolumeAttribute
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ec2:DeleteInternetGateway
                Resource:
                  - !Sub arn:aws:ec2:*:${AWS::AccountId}:internet-gateway/*
              - Effect: Allow
                Action:
                  - ec2:DeleteSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:AuthorizeSecurityGroupEgress
                Resource:
                  - !Sub arn:aws:ec2:*:${AWS::AccountId}:security-group/*
        #kms
        - PolicyName: kms-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:ScheduleKeyDeletion
                  - kms:DescribeKey
                  - kms:PutKeyPolicy
                  - kms:ListResourceTags
                  - kms:TagResource
                  - kms:UntagResource
                  - kms:CreateAlias
                  - kms:DeleteAlias
                  - kms:CreateGrant
                  - kms:GenerateDataKey*
                  - kms:Encrypt
                  - kms:ReEncrypt*
                  - kms:Decrypt
                  - kms:UpdateAlias
                  - kms:*Rotation*
                Resource:
                  - !Sub arn:aws:kms:*:${AWS::AccountId}:key/*
                  - !Sub arn:aws:kms:*:${AWS::AccountId}:alias/*
        #s3
        - PolicyName: s3-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - arn:aws:s3:::*
        #codebuild?
        - PolicyName: codebuild-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:*
                Resource:
                  - '*'

Outputs:
  TargetAccountCFRoleArn:
    Description: 'arn of ops'
    Value: !GetAtt CloudformationDeploymentRole.Arn
