import boto3
import pandas as pd

users_and_services = {
    "abigael.alba.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, Amazon EventBridge, AWS Key Management Service, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Security Token Service",
    "agustin.espindola.": "Amazon EC2 Auto Scaling, Amazon EventBridge, AWS Key Management Service, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SNS, Amazon SQS",
    "ahmed.hassan.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, Amazon SNS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "alex.gutnik.": "AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon RDS, AWS Secrets Manager, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "alex.kolodiazhnyi.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, AWS Elastic Beanstalk, AWS OpsWorks, Amazon Redshift Data API, AWS Serverless Application Repository",
    "alexander.borohov.": "AWS CodeStar Connections, Amazon SES",
    "alexander.shostak.": "AWS CodeStar Connections, Amazon DevOps Guru, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository",
    "alexandru.olaru.": "AWS CodeStar Connections, AWS CodeStar Notifications, AWS Serverless Application Repository",
    "ali.toshpulatov.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "allamyrat.bayramov.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API",
    "ameer.hamza.": "Manage - Amazon API Gateway, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, Amazon RDS, AWS Systems Manager, AWS Support",
    "an.kong.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "anastasiia.zaporozhets.": "Amazon EC2 Auto Scaling, Amazon EventBridge, AWS Key Management Service, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SNS, Amazon SQS",
    "andrei.yarashonak.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon RDS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "andrew.santos.": "Amazon EventBridge, AWS Key Management Service, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SQS",
    "andrey.neprel.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon Comprehend, Amazon DevOps Guru, Elastic Load Balancing, Amazon CloudWatch Observability Access Manager, AWS Performance Insights, Amazon Redshift, AWS Serverless Application Repository, AWS Systems Manager, AWS Step Functions",
    "andrii.bilous.": "Amazon DevOps Guru, Amazon SQS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "andrii.didkivskyi.": "Manage - Amazon API Gateway, Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeStar Connections, Amazon DevOps Guru, Elastic Load Balancing, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, Amazon S3, AWS Serverless Application Repository, Amazon SNS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "andrii.lebedenko.": "Amazon DevOps Guru, AWS Elastic Beanstalk, Elastic Load Balancing, Amazon EventBridge, Amazon Kinesis Firehose, AWS OpsWorks, Amazon RDS",
    "andrii.pivovarov.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeStar Connections, Amazon DevOps Guru, Elastic Load Balancing, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "anu.sambath.": "Amazon EC2 Auto Scaling, Elastic Load Balancing, Amazon Redshift, AWS Serverless Application Repository, Amazon SNS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service",
    "arsalan.mudni.": "Amazon EC2 Auto Scaling, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon Redshift Data API",
    "arvit.varfaj.": "Manage - Amazon API Gateway, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon RDS, Amazon SES, AWS Step Functions, AWS Security Token Service, AWS X-Ray",
    "bagzhan.sadvakassov.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "barbara.britto.": "Amazon EventBridge, AWS Key Management Service, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SQS",
    "bilal.ahmedyaseen.": "Manage - Amazon API Gateway, AWS X-Ray",
    "bin.jia.": "Amazon CloudWatch, AWS CodeCommit, AWS Database Migration Service, Amazon EC2, Amazon Kinesis Firehose, AWS Identity and Access Management, AWS Key Management Service, Amazon CloudWatch Logs, Amazon Redshift, Amazon S3, AWS Systems Manager",
    "bogdan.kischak.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon RDS, AWS Serverless Application Repository",
    "bruno.ksouza.": "Amazon EC2 Auto Scaling, Amazon EventBridge, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, Amazon SNS",
    "bruno.larentis.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon S3, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "camilo.pinzon.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, Amazon EventBridge, AWS Key Management Service, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SNS, Amazon SQS",
    "cdl.dev-prev-dr.landing.": "Amazon S3",
    "danyal.sandeelo.": "Manage - Amazon API Gateway, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "DCS3Browser.": "Amazon S3 Glacier",
    "dev-quicksight-admin.": "Amazon QuickSight",
    "dmitrii.andropov.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "dmitriy.muzychuk.": "Amazon EC2 Auto Scaling, AWS CodeBuild, AWS CodeDeploy, AWS CodePipeline, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon RDS, Amazon Redshift, AWS Serverless Application Repository, Amazon SNS, AWS Systems Manager, AWS Step Functions, AWS X-Ray",
    "dmytro.khlevniak.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon S3 Object Lambda, AWS Serverless Application Repository",
    "dmytro.sokolov.": "Amazon EC2 Auto Scaling, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "dong.yang.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeStar Connections, Amazon DevOps Guru, AWS Lambda, Amazon RDS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "dong.zhou.": "AWS CloudFormation, AWS CodeStar Connections, Amazon DevOps Guru, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "eric.christensen.": "AWS CloudFormation, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon OpenSearch Service, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "evgeny.aleksanov.": "AWS CodeStar Connections, Amazon OpenSearch Service",
    "fakhriddin.umarov.": "AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon RDS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "felipe.ladik.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "german.rodriguez.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, Amazon SQS",
    "giorgi.khmaladze.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "Grafana.": "Alexa for Business, AWS IAM Access Analyzer, AWS Account Management, AWS Certificate Manager, AWS Private Certificate Authority, Amazon Managed Workflows for Apache Airflow, AWS Amplify, Manage - Amazon API Gateway, AWS AppConfig, Amazon AppFlow, AWS Application Auto Scaling, Amazon CloudWatch Application Insights, AWS App Mesh, AWS App Runner, Amazon AppStream 2.0, AWS AppSync, Amazon Managed Service for Prometheus, Amazon Route 53 Application Recovery Controller - Zonal Shift, AWS Artifact, Amazon Athena, AWS Audit Manager, Amazon EC2 Auto Scaling, AWS Auto Scaling, AWS Billing Console, AWS Backup, AWS Backup Gateway, AWS Batch, AWS Billing , AWS Billing Conductor, Amazon Braket, AWS Budget Service, Amazon Keyspaces (for Apache Cassandra), AWS Cost Explorer Service, AWS Chatbot, Amazon Chime, AWS Clean Rooms, AWS Cloud9, Amazon Cloud Directory, AWS CloudFormation, Amazon CloudFront, AWS CloudHSM, Amazon CloudSearch, AWS CloudTrail, AWS CodeArtifact, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, Amazon CodeGuru Profiler, Amazon CodeGuru Reviewer, AWS CodePipeline, AWS CodeStar, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon Cognito Identity, Amazon Cognito User Pools, Amazon Cognito Sync, Amazon Comprehend, AWS Compute Optimizer, AWS Config, Amazon Connect, AWS Consolidated Billing, AWS Glue DataBrew, AWS Data Exchange, AWS Data Pipeline, AWS DataSync, Amazon DynamoDB Accelerator (DAX), AWS DeepComposer, Amazon Detective, AWS Device Farm, Amazon DevOps Guru, AWS Direct Connect, AWS Application Discovery Service, Amazon Data Lifecycle Manager, AWS Database Migration Service, AWS Elastic Disaster Recovery, AWS Directory Service, Amazon DynamoDB, Amazon Message Delivery Service, Amazon Elastic Container Registry, Amazon Elastic Container Registry Public, Amazon Elastic Container Service, Amazon Elastic Kubernetes Service, Amazon Elastic Inference, Amazon ElastiCache, AWS Elastic Beanstalk, Amazon Elastic File System, Elastic Load Balancing, Amazon Elastic MapReduce, Amazon Elastic Transcoder, AWS Elemental Appliances and Software, Amazon EMR on EKS (EMR Containers), Amazon OpenSearch Service, Amazon EventBridge, Amazon CloudWatch Evidently, Amazon Kinesis Firehose, AWS Fault Injection Simulator, AWS Firewall Manager, Amazon Forecast, Amazon Fraud Detector, Amazon FreeRTOS, AWS Free Tier, Amazon FSx, Amazon GameLift, Amazon GameSparks, Amazon S3 Glacier, AWS Global Accelerator, AWS Glue, Amazon Managed Grafana, AWS IoT Greengrass, AWS Ground Station, Amazon GuardDuty, AWS Health APIs and Notifications, Amazon HealthLake, AWS Identity and Access Management, AWS Identity Sync, AWS Identity Store Auth, Amazon EC2 Image Builder, AWS Import Export, Amazon Inspector, Amazon Inspector2, Amazon CloudWatch Internet Monitor, AWS Invoicing Service, AWS IoT, AWS IoT 1-Click, AWS IoT Analytics, AWS IoT Events, AWS IoT Fleet Hub for Device Management, AWS IoT FleetWise, AWS IoT RoboRunner, AWS IoT SiteWise, AWS IoT Wireless, Amazon Interactive Video Service, Amazon Interactive Video Service Chat, Amazon Managed Streaming for Apache Kafka, Amazon Managed Streaming for Kafka Connect, Amazon Kendra, Amazon Kinesis Data Streams, Amazon Kinesis Analytics, Amazon Kinesis Video Streams, AWS Key Management Service, AWS Lambda, Amazon Lex, AWS License Manager, Amazon Lightsail, Amazon CloudWatch Logs, Amazon Lookout for Equipment, Amazon Lookout for Metrics, Amazon Lookout for Vision, AWS Mainframe Modernization Service, Amazon Machine Learning, Amazon Macie, Amazon Managed Blockchain, AWS Elemental MediaConnect, AWS Elemental MediaConvert, AWS Elemental MediaLive, AWS Elemental MediaPackage, AWS Elemental MediaPackage VOD, AWS Elemental MediaStore, Amazon MemoryDB, AWS Migration Hub, AWS Application Migration Service, Amazon Mobile Analytics, Amazon Pinpoint, Amazon Monitron, Amazon MQ, AWS Network Firewall, AWS Network Manager, Amazon Nimble Studio, Amazon CloudWatch Observability Access Manager, AWS OpsWorks, AWS OpsWorks Configuration Management, AWS Organizations, AWS Outposts, AWS Payments, Amazon Personalize, AWS Performance Insights, Amazon Polly, AWS Proton, AWS Purchase Orders Console, Amazon QLDB, AWS Resource Access Manager, AWS Recycle Bin, Amazon Redshift, AWS Migration Hub Refactor Spaces, Amazon Rekognition, AWS Resilience Hub Service, AWS Resource Explorer, AWS Resource Groups, AWS RoboMaker, Amazon Route 53, Amazon Route 53 Recovery Cluster, Amazon Route 53 Recovery Controls, Amazon Route 53 Recovery Readiness, Amazon Route 53 Domains, Amazon Route 53 Resolver, AWS CloudWatch RUM, Amazon S3",
    "guangchao.yi.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon DevOps Guru, AWS Lambda, Amazon RDS, Amazon SNS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "guanggeng.li.": "AWS CodeStar Connections, Amazon DevOps Guru, Amazon RDS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "gustavo.rodrigues.": "Amazon EC2 Auto Scaling, Amazon EventBridge, AWS Key Management Service, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Security Token Service",
    "hai.li.": "AWS Security Token Service",
    "haijun.lei.": "AWS Security Token Service",
    "hakob.grigoryan.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeDeploy, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "herman.kliushyn.": "AWS CodeStar Connections, Amazon DevOps Guru, Amazon Redshift Data API, AWS Serverless Application Repository, AWS X-Ray",
    "hongpeng.wu.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "hovhannes.baghdasaryan.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "huizhe.mi.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "iam_cleanup_user.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeBuild, AWS Key Management Service, AWS Lambda, AWS Organizations, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS",
    "iegor.ryzhenko.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "ihor.kozhevnikov.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Step Functions, AWS X-Ray",
    "illia.kantsevich.": "Amazon EC2 Auto Scaling, AWS CodeStar Connections, AWS CodeStar Notifications, AWS Performance Insights, Amazon Redshift, AWS Serverless Application Repository",
    "ivan.patritskiy.": "Manage - Amazon API Gateway, Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, Amazon S3, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "ivan.stetsenko.": "Manage - Amazon API Gateway, Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, Amazon S3, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "ivan.telichkin.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon OpenSearch Service, Amazon RDS, Amazon Redshift, AWS X-Ray",
    "james.song.": "Amazon EC2 Auto Scaling, Amazon SNS",
    "jason.zhang.": "AWS CloudFormation, AWS CodeBuild, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "jianjiao.zheng.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, AWS CodeCommit, AWS Identity and Access Management, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon S3, Amazon SNS, AWS Security Token Service",
    "jie.huang.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "jin.min.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "jixiang.wang.": "Amazon EC2 Auto Scaling, Amazon CloudWatch Observability Access Manager, Amazon SNS",
    "karina.trondina.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon RDS, Amazon Redshift, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "kasi.dogga.": "AWS CloudFormation, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon S3, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "kirill.sergeev.": "Manage - Amazon API Gateway, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Elastic Load Balancing, AWS Serverless Application Repository, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "konstantin.serdiuk.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon API Gateway, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, AWS Step Functions",
    "kostyantyn.yermashov.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeDeploy, AWS CodePipeline, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, AWS Serverless Application Repository, Amazon SNS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "krisan.timur.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, Amazon RDS, AWS Step Functions",
    "leandro.campora.": "Amazon EC2 Auto Scaling, AWS CodeDeploy, AWS CodeStar Connections, Amazon DevOps Guru, Amazon EventBridge, Amazon RDS, Amazon Redshift Data API, AWS Serverless Application Repository, Amazon SNS, AWS X-Ray",
    "leizong.yu.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "leonardo.garcia.": "Amazon EC2 Auto Scaling, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, Amazon RDS, Amazon Redshift, Amazon S3, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS X-Ray",
    "li.xiaodong.": "AWS Security Token Service",
    "liehong.hu.": "Amazon EC2 Auto Scaling, Amazon CloudWatch Observability Access Manager, Amazon SNS",
    "ling.li.": "AWS Identity and Access Management",
    "liu.jing.": "AWS CodeCommit, AWS Identity and Access Management",
    "liudmyla.koval.": "AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "luciana.gay.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "luciano.bustos.": "AWS CodeStar Connections, Amazon DevOps Guru, Amazon Redshift Data API, AWS Serverless Application Repository",
    "marcos.vinicius.": "Amazon EventBridge, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, Amazon SQS",
    "matheus.franco.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, Amazon EventBridge, AWS Key Management Service, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Security Token Service",
    "matko.klaic.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, Amazon Textract, AWS X-Ray",
    "maxim.gamurar.": "AWS CodeStar Connections, AWS Performance Insights, Amazon Redshift, AWS Serverless Application Repository, Amazon Resource Group Tagging API, AWS X-Ray",
    "michael.michailidis.": "Manage - Amazon API Gateway, Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, Amazon S3, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "michele.cherry.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "michelle.alves.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, Amazon EventBridge, AWS Key Management Service, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Security Token Service",
    "mingxing.xia.": "AWS Security Token Service",
    "mohannad.farhoud.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SES, Amazon SQS, AWS Systems Manager, Amazon Resource Group Tagging API, AWS X-Ray",
    "mohsin.raza.": "Amazon EC2 Auto Scaling, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon Redshift Data API, Amazon SES",
    "muhammad.asad.": "Amazon EC2 Auto Scaling, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon RDS, AWS Systems Manager, AWS Step Functions, AWS X-Ray",
    "muhammad.razzaq.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "myroslav.kuzmych.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "nanyi.wang.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "nataliia.savruk.": "Amazon EventBridge, AWS Key Management Service, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SQS",
    "natanael.vallejos.": "Amazon EC2 Auto Scaling, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Support, AWS X-Ray",
    "ngangomfg.vongue.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, Amazon S3, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "nihir.kumar.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift Data API, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "nikolay.mnatsakanyan.": "Amazon EC2 Auto Scaling, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon RDS, Amazon Redshift, Amazon S3, AWS Serverless Application Repository, Amazon SNS, Amazon SQS",
    "nikoloz.razmadze.": "Manage - Amazon API Gateway, Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodePipeline, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, AWS Elastic Beanstalk, Elastic Load Balancing, Amazon OpenSearch Service, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, AWS OpsWorks, Amazon RDS, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "noman.tufail.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeDeploy, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon S3, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "noman.yaqoob.": "Amazon EC2 Auto Scaling, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon RDS, Amazon Redshift, AWS Serverless Application Repository, Amazon SNS, AWS Systems Manager",
    "obed.amoasi.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeStar Connections, Amazon DevOps Guru, Elastic Load Balancing, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, Amazon SNS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "oksana.desiatnykova.": "Manage - Amazon API Gateway, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SES, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "oleh.perushko.": "AWS CodeStar Connections, Amazon Cognito Identity, Amazon Cognito Sync, AWS IoT",
    "oleksandra.trylevych.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "olga.dniprovska.": "AWS Identity and Access Management, Amazon S3",
    "osman.gafarov.": "AWS CodeStar Connections, AWS CodeStar Notifications, AWS Elastic Beanstalk, AWS OpsWorks, AWS Serverless Application Repository",
    "paulo.nunes.": "Amazon EC2 Auto Scaling, Amazon EventBridge, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, Amazon SNS, Amazon SQS",
    "paulo.silva.": "Amazon EC2 Auto Scaling, Amazon EventBridge, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, Amazon SNS, Amazon SQS",
    "pavlo.pavlenko.": "Manage - Amazon API Gateway, Amazon DevOps Guru, Amazon RDS, AWS Step Functions, AWS X-Ray",
    "pavlo.sobchuk.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodePipeline, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, AWS Elastic Beanstalk, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, AWS OpsWorks, Amazon RDS, Amazon Redshift, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "pengcheng.chen.": "AWS Security Token Service",
    "pfizer-hackathon-s3.": "Amazon S3",
    "pingyang.li.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon OpenSearch Service, Amazon CloudWatch Observability Access Manager, AWS Step Functions, AWS X-Ray",
    "punkuz.shah.": "Amazon EC2 Auto Scaling, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, AWS X-Ray",
    "qinmao.zhu.": "AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon OpenSearch Service, Amazon EventBridge, AWS Lambda, Amazon RDS, AWS Step Functions, AWS X-Ray",
    "ramkrishna.kc.": "AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon RDS, AWS Serverless Application Repository, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "raphael.palmer.": "Amazon CloudWatch Logs",
    "robert.siket.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon OpenSearch Service",
    "rodion.batiushkov.": "AWS CodeStar Connections, Amazon Cognito Identity, Amazon Cognito Sync, Amazon DevOps Guru, Amazon DynamoDB, AWS IoT, Amazon Kinesis Data Streams",
    "rodion.chernyshov.": "Manage - Amazon API Gateway, Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "roman.luzin.": "AWS CodeStar Connections, Elastic Load Balancing, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository",
    "ruslan.shayakhmetov.": "Manage - Amazon API Gateway, AWS CodeStar Connections, Amazon DevOps Guru, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, AWS Systems Manager, AWS Step Functions, AWS X-Ray",
    "saidamirkhon.abdulloev.": "Manage - Amazon API Gateway, AWS CloudFormation, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "samuel.ako.": "Manage - Amazon API Gateway, Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon DevOps Guru, Elastic Load Balancing, AWS Lambda, Amazon RDS, AWS Serverless Application Repository, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "semion.simkin.": "AWS CodeStar Connections, AWS CodeStar Notifications, Elastic Load Balancing, Amazon OpenSearch Service, Amazon EventBridge, Amazon Kinesis Firehose, Amazon Redshift Data API, AWS Secrets Manager, Amazon SQS, AWS Systems Manager, AWS X-Ray",
    "sergei.dubrov.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "sergey.kovalchuk.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, Amazon RDS",
    "sergey.kuznetsov.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon OpenSearch Service, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "sergey.lem.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, AWS X-Ray",
    "serhii.zghama.": "Manage - Amazon API Gateway, AWS CodeStar Connections, Amazon DevOps Guru, Amazon Redshift Data API, AWS Serverless Application Repository, AWS Support, AWS X-Ray",
    "ses-smtp-user.upsource.": "Amazon SES",
    "siarhei.kushner.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeDeploy, AWS CodePipeline, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon RDS, Amazon Redshift, Amazon S3, AWS Serverless Application Repository, Amazon SNS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "siarhey.filipau.": "Manage - Amazon API Gateway, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon CloudWatch Observability Access Manager, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, AWS Systems Manager, AWS Step Functions, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "srdjan.cengic.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodePipeline, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon S3, AWS Serverless Application Repository, Amazon SNS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "stefan.muntean.": "AWS CloudFormation, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon RDS, AWS Secrets Manager, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API",
    "stefan.onisoru.": "Amazon EventBridge, AWS Key Management Service, Amazon CloudWatch Observability Access Manager, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, AWS Secrets Manager, Amazon SQS",
    "stepan.kasyanenko.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodePipeline, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon S3, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "tatyana.repicheva.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon RDS, Amazon Redshift, Amazon S3, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS X-Ray",
    "test.account.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "test.temp.": "Manage - Amazon API Gateway, Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon OpenSearch Service, Amazon EventBridge, AWS Identity and Access Management, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, Amazon SES, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "tetiana.molchanova.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "thaylor.carvalho.": "Amazon EC2 Auto Scaling, Amazon EventBridge, AWS Key Management Service, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas, Amazon SNS, Amazon SQS",
    "tomas.monteroswinnen.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "uktam.mansurov.": "Manage - Amazon API Gateway, AWS CodeStar Connections, AWS CodeStar Notifications, AWS Elastic Beanstalk, Amazon EventBridge, AWS OpsWorks, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, Amazon SES, AWS Step Functions, AWS X-Ray",
    "usama.nazir.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Security Token Service, AWS Support, AWS X-Ray",
    "vasiliy.gavrilov.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon OpenSearch Service, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "vasyl.protsukovych.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "viachaslau.shalkevich.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "victoria.ryabchikova.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon S3, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "vinicius.barros.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "vishvesh.gowrising.": "Manage - Amazon API Gateway",
    "vitalii.zavarskii.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "vlad.butnaru.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "vladimir.makarenko.": "Manage - Amazon API Gateway, AWS CodeStar Connections, Elastic Load Balancing, Amazon EventBridge, Amazon Redshift, AWS Serverless Application Repository, Amazon SES, AWS Systems Manager, AWS Step Functions, AWS X-Ray",
    "vladyslav.bakhin.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS X-Ray",
    "vladyslav.kudenko.": "AWS CodeStar Connections, Amazon Kinesis Firehose, Amazon SQS, AWS X-Ray",
    "walter.ochipinti.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "wei.pei.": "Amazon EC2 Auto Scaling, AWS CodeCommit, Amazon CloudWatch Observability Access Manager, Amazon SNS",
    "wenli.zhang.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon SNS",
    "wentao.zhao.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "xi.wang.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, AWS CodeCommit, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon SNS",
    "xianbang.hu.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "xiaowu.qin.": "AWS CloudFormation, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Secrets Manager, Amazon SNS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "yao.xiao.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Identity and Access Management, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "yevhen.kovalevskyi.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon S3, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "yi.zhang.": "AWS CloudFormation, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "yiming.tao.": "Amazon EC2 Auto Scaling, Amazon CloudWatch, AWS CodeCommit, AWS Identity and Access Management, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon SNS, AWS Security Token Service",
    "yuanlin.wu.": "AWS Identity and Access Management, AWS Security Token Service",
    "yuanling.tan.": "AWS Identity and Access Management, AWS Security Token Service",
    "yueqiao.meng.": "Amazon SNS",
    "yuliia.pronchuk.": "Amazon EventBridge, Amazon EventBridge Pipes, Amazon EventBridge Scheduler, Amazon EventBridge Schemas",
    "yurii.hats.": "AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, Amazon CloudWatch Observability Access Manager, Amazon RDS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API",
    "yuriy.baturin.": "Manage - Amazon API Gateway, AWS CloudFormation, Amazon DevOps Guru, Elastic Load Balancing, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, Amazon SQS, AWS Systems Manager, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "yuriy.gurin.": "Amazon EC2 Auto Scaling, AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Step Functions, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "yuriy.matyashev.": "AWS CodeStar Connections, AWS CodeStar Notifications, Amazon SES",
    "zeeshan.aziz.": "Amazon EC2 Auto Scaling, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon RDS, Amazon Redshift, AWS Serverless Application Repository, Amazon SNS, AWS Systems Manager, AWS X-Ray",
    "zhixue.wu.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon S3, AWS Secrets Manager, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, Amazon Resource Group Tagging API, AWS X-Ray",
    "zilong.zhang.": "AWS CloudFormation, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon SNS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "zoriana.kovacs.": "Manage - Amazon API Gateway, Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeBuild, AWS CodeCommit, AWS CodeDeploy, AWS CodePipeline, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon EC2, Elastic Load Balancing, Amazon EventBridge, AWS Key Management Service, AWS Lambda, Amazon CloudWatch Logs, Amazon CloudWatch Observability Access Manager, AWS Performance Insights, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, Amazon S3, AWS Secrets Manager, AWS Serverless Application Repository, Amazon SNS, Amazon SQS, AWS Systems Manager, AWS Step Functions, AWS Security Token Service, AWS Support, Amazon Resource Group Tagging API, AWS X-Ray",
    "zorik.zakaryan.": "Amazon EC2 Auto Scaling, AWS CloudFormation, Amazon CloudWatch, AWS CodeDeploy, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Elastic Load Balancing, Amazon EventBridge, AWS Lambda, Amazon CloudWatch Observability Access Manager, Amazon RDS, Amazon Redshift, Amazon S3, AWS Serverless Application Repository, Amazon SNS, AWS Step Functions, Amazon Resource Group Tagging API, AWS X-Ray",
    "zuobang.zhang.": "Manage - Amazon API Gateway, AWS CloudFormation, AWS CodeDeploy, AWS CodePipeline, AWS CodeStar Connections, AWS CodeStar Notifications, Amazon DevOps Guru, Amazon OpenSearch Service, Amazon EventBridge, AWS Lambda, Amazon RDS, Amazon Redshift, Amazon Redshift Data API, AWS Serverless Application Repository, AWS Step Functions",
}

service_mapping = {
    'AWS Resource Explorer': 'resource-explorer',
    'AWS Data Exchange': 'dataexchange',
    'AWS Elemental MediaConnect': 'mediaconnect',
    'AWS IoT Wireless': 'iotwireless',
    'Amazon DynamoDB Accelerator (DAX)': 'dynamodb',
    'Amazon Route 53 Recovery Controls': 'route53',
    'Amazon Macie': 'macie',
    'AWS Network Manager': 'networkmanager',
    'AWS CodeCommit': 'codecommit',
    'AWS Cost Explorer Service': 'ce',
    'AWS Identity and Access Management': 'iam',
    'Amazon Elastic File System': 'elasticfilesystem',
    'AWS Consolidated Billing': 'aws-portal',
    'Amazon Keyspaces (for Apache Cassandra)': 'cassandra',
    'AWS CodeStar Notifications': 'codestar-notifications',
    'Amazon GuardDuty': 'guardduty',
    'Amazon Redshift Data API': 'redshift-data',
    'Amazon EC2': 'ec2',
    'AWS Organizations': 'organizations',
    'Amazon EventBridge': 'events',
    'AWS Auto Scaling': 'autoscaling',
    'Amazon Detective': 'detective',
    'AWS CloudHSM': 'cloudhsm',
    'Amazon EMR on EKS (EMR Containers)': 'emr-containers',
    'Amazon Kinesis Data Streams': 'kinesis',
    'Amazon Nimble Studio': 'nimble',
    'AWS CodePipeline': 'codepipeline',
    'AWS OpsWorks': 'opsworks',
    'Amazon EC2 Image Builder': 'imagebuilder',
    'Amazon CloudWatch Application Insights': 'applicationinsights',
    'Amazon Rekognition': 'rekognition',
    'AWS Backup Gateway': 'storagegateway',
    'AWS Lambda': 'lambda',
    'AWS Recycle Bin': 'aws-global',
    'Amazon CodeGuru Reviewer': 'codeguru-reviewer',
    'Amazon FSx': 'fsx',
    'Amazon EventBridge Scheduler': 'events',
    'Amazon GameLift': 'gamelift',
    'AWS Cloud9': 'cloud9',
    'AWS App Runner': 'apprunner',
    'AWS Billing Console': 'aws-portal',
    'AWS OpsWorks Configuration Management': 'opsworks-cm',
    'AWS Systems Manager': 'ssm',
    'Amazon Mobile Analytics': 'mobileanalytics',
    'Amazon Cognito Identity': 'cognito-identity',
    'Amazon S3 Object Lambda': 's3-object-lambda',
    'Amazon FreeRTOS': 'freertos',
    'Amazon Chime': 'chime',
    'Amazon Kendra': 'kendra',
    'AWS Identity Sync': 'identitystore',
    'AWS IoT Events': 'iotevents',
    'AWS Health APIs and Notifications': 'health',
    'Amazon Lightsail': 'lightsail',
    'Amazon QuickSight': 'quicksight',
    'Amazon Braket': 'braket',
    'Amazon CodeGuru Profiler': 'codeguru-profiler',
    'AWS Amplify': 'amplify',
    'AWS CodeStar Connections': 'codestar-connections',
    'Amazon AppFlow': 'appflow',
    'AWS Key Management Service': 'kms',
    'Amazon OpenSearch Service': 'es',
    'Amazon Interactive Video Service Chat': 'ivs',
    'Amazon EventBridge Pipes': 'events',
    'AWS IoT Greengrass': 'greengrass',
    'Amazon CloudWatch Observability Access Manager': 'cloudwatch',
    'Amazon Elastic Kubernetes Service': 'eks',
    'Amazon MemoryDB': 'memorydb',
    'AWS Config': 'config',
    'AWS Clean Rooms': 'cleanrooms',
    'Amazon Kinesis Firehose': 'firehose',
    'AWS RoboMaker': 'robomaker',
    'Amazon Textract': 'textract',
    'Amazon Managed Blockchain': 'managedblockchain',
    'AWS CodeDeploy': 'codedeploy',
    'Amazon Route 53 Application Recovery Controller - Zonal Shift': 'route53-recovery',
    'AWS Resource Groups': 'resource-groups',
    'AWS Private Certificate Authority': 'acm-pca',
    'Amazon Machine Learning': 'machinelearning',
    'AWS Secrets Manager': 'secretsmanager',
    'Amazon Route 53 Domains': 'route53',
    'AWS Purchase Orders Console': 'aws-purchase-orders',
    'AWS Fault Injection Simulator': 'fis',
    'AWS AppSync': 'appsync',
    'AWS Billing Conductor': 'billingconsole',
    'AWS Migration Hub Refactor Spaces': 'mgn',
    'Amazon Inspector2': 'inspector',
    'Alexa for Business': 'a4b',
    'AWS Elemental MediaPackage VOD': 'mediapackage-vod',
    'AWS Database Migration Service': 'dms',
    'Amazon Managed Streaming for Apache Kafka': 'kafka',
    'AWS Invoicing Service': 'aws-invoicing',
    'Elastic Load Balancing': 'elasticloadbalancing',
    'AWS Ground Station': 'groundstation',
    'Amazon CloudWatch Logs': 'logs',
    'AWS Performance Insights': 'pi',
    'AWS Network Firewall': 'network-firewall',
    'AWS IoT': 'iot',
    'Amazon Route 53 Resolver': 'route53resolver',
    'AWS Elemental MediaPackage': 'mediapackage',
    'Amazon Data Lifecycle Manager': 'dlm',
    'AWS Resource Access Manager': 'ram',
    'AWS Device Farm': 'devicefarm',
    'AWS CloudWatch RUM': 'cloudwatchrum',
    'AWS Elemental MediaConvert': 'mediaconvert',
    'AWS Account Management': 'account',
    'Amazon API Gateway': 'apigateway',
    'AWS Application Auto Scaling': 'application-autoscaling',
    'AWS CodeArtifact': 'codeartifact',
    'Amazon CloudWatch': 'cloudwatch',
    'Amazon MQ': 'mq',
    'AWS License Manager': 'license-manager',
    'Amazon QLDB': 'qldb',
    'AWS Step Functions': 'states',
    'Amazon Elastic Container Registry': 'ecr',
    'AWS Direct Connect': 'directconnect',
    'Amazon Cloud Directory': 'clouddirectory',
    'AWS App Mesh': 'appmesh',
    'Amazon Redshift': 'redshift',
    'AWS DeepComposer': 'deepcomposer',
    'Amazon EventBridge Schemas': 'schemas',
    'Amazon Elastic Container Service': 'ecs',
    'AWS IoT RoboRunner': 'iot-robot-runner',
    'AWS Payments': 'payments',
    'Amazon Kinesis Video Streams': 'kinesisvideo',
    'AWS Billing': 'aws-marketplace',
    'Amazon Cognito Sync': 'cognito-sync',
    'AWS Outposts': 'outposts',
    'AWS Glue DataBrew': 'databrew',
    'Amazon Fraud Detector': 'frauddetector',
    'Amazon CloudSearch': 'cloudsearch',
    'AWS Elastic Disaster Recovery': 'disaster-recovery',
    'AWS Firewall Manager': 'fms',
    'AWS CloudTrail': 'cloudtrail',
    'AWS Batch': 'batch',
    'AWS Elastic Beanstalk': 'elasticbeanstalk',
    'Amazon Monitron': 'monitron',
    'Amazon Resource Group Tagging API': 'tag',
    'AWS Resilience Hub Service': 'resilience',
    'Amazon CloudWatch Internet Monitor': 'net-analyzer',
    'AWS Elemental MediaLive': 'medialive',
    'AWS IAM Access Analyzer': 'access-analyzer',
    'AWS Global Accelerator': 'globalaccelerator',
    'Amazon Managed Workflows for Apache Airflow': 'airflow',
    'AWS IoT Analytics': 'iotanalytics',
    'Amazon Interactive Video Service': 'ivs',
    'AWS Support': 'support',
    'Amazon Lookout for Equipment': 'lookoutequipment',
    'AWS X-Ray': 'xray',
    'Amazon DynamoDB': 'dynamodb',
    'AWS IoT Fleet Hub for Device Management': 'iotfleethub',
    'AWS IoT FleetWise': 'iotfleetwise',
    'Amazon SES': 'ses',
    'Amazon Lookout for Vision': 'lookoutvision',
    'AWS Budget Service': 'budgets',
    'Amazon Personalize': 'personalize',
    'Amazon Managed Grafana': 'grafana',
    'Amazon RDS': 'rds',
    'Amazon CloudFront': 'cloudfront',
    'Amazon Comprehend Medical': 'comprehendmedical',
    'AWS AppConfig': 'appconfig',
    'Amazon Connect': 'connect',
    'AWS Glue': 'glue',
    'Amazon Route 53 Recovery Readiness': 'route53-recovery-readiness',
    'Amazon SNS': 'sns',
    'AWS Data Pipeline': 'datapipeline',
    'AWS Migration Hub': 'mgh',
    'AWS Serverless Application Repository': 'serverlessrepo',
    'AWS CodeStar': 'codestar',
    'Amazon SQS': 'sqs',
    'Amazon Inspector': 'inspector',
    'AWS Certificate Manager': 'acm',
    'AWS Audit Manager': 'auditmanager',
    'Amazon Cognito User Pools': 'cognito-idp',
    'AWS Identity Store Auth': 'identitystore',
    'Amazon Managed Streaming for Kafka Connect': 'kafkaconnect',
    'Amazon CloudWatch Evidently': 'evidentlymetrics',
    'AWS Chatbot': 'chatbot',
    'AWS Proton': 'proton',
    'Amazon S3 Glacier': 'glacier',
    'Amazon Pinpoint': 'mobiletargeting',
    'Amazon Route 53 Recovery Cluster': 'route53-recovery-cluster',
    'Amazon Elastic Container Registry Public': 'ecr-public',
    'Manage - Amazon API Gateway': 'execute-api',
    'AWS IoT 1-Click': 'iot1click',
    'AWS Application Migration Service': 'mgn',
    'Amazon GameSparks': 'gamesparks',
    'AWS CloudFormation': 'cloudformation',
    'Amazon Lex': 'lex',
    'Amazon Managed Service for Prometheus': 'aps',
    'Amazon ElastiCache': 'elasticache',
    'Amazon Kinesis Analytics': 'kinesisanalytics',
    'AWS Application Discovery Service': 'discovery',
    'Amazon Forecast': 'forecast',
    'AWS Artifact': 'artifact',
    'Amazon EC2 Auto Scaling': 'autoscaling',
    'AWS Backup': 'backup',
    'Amazon Polly': 'polly',
    'AWS Elemental Appliances and Software': 'elemental',
    'Amazon HealthLake': 'healthlake',
    'AWS DataSync': 'datasync',
    'AWS Mainframe Modernization Service': 'aws-mainframe-modernization',
    'Amazon Elastic MapReduce': 'elasticmapreduce',
    'AWS Compute Optimizer': 'compute-optimizer',
    'Amazon AppStream 2.0': 'appstream',
    'Amazon Message Delivery Service': 'ec2message',
    'AWS Import Export': 'importexport',
    'Amazon Route 53': 'route53',
    'Amazon S3': 's3',
    'AWS CodeBuild': 'codebuild',
    'Amazon Comprehend': 'comprehend',
    'Amazon Elastic Inference': 'elastic-inference',
    'AWS Free Tier': 'aws-free-tier',
    'AWS IoT SiteWise': 'iotsitewise',
    'Amazon Lookout for Metrics': 'lookoutmetrics',
    'Amazon Elastic Transcoder': 'elastictranscoder',
    'AWS Security Token Service': 'sts',
    'AWS Directory Service': 'ds',
    'Amazon DevOps Guru': 'devops-guru',
    'Amazon Athena': 'athena',
    'AWS Elemental MediaStore': 'mediastore'
}

usernames = list(users_and_services.keys())
iam = boto3.client('iam')
df = pd.DataFrame(columns=['Username', 'ServiceNamespace', 'PolicyName', 'PolicyType', 'PolicyArn', 'EntityType', 'EntityName'])

for username in usernames:
    if '.' not in username[:-1] or '-' in username:
        continue
    userArn = iam.get_user(UserName=username[:-1])['User']['Arn']
    services = [element.strip() for element in users_and_services[username].split(',')]
    service_namespaces = [service_mapping[element] for element in services]
    marker = None
    while True:
        if marker:
            response = iam.list_policies_granting_service_access(Arn=userArn, ServiceNamespaces=service_namespaces,
                                                                 Marker=marker)['PoliciesGrantingServiceAccess']
        else:
            response = iam.list_policies_granting_service_access(Arn=userArn, ServiceNamespaces=service_namespaces)['PoliciesGrantingServiceAccess']
        for item in response:
            for policy in item['Policies']:
                df = pd.concat([df, pd.DataFrame({'Username': [username[:-1]],
                                                  'ServiceNamespace': [item['ServiceNamespace']],
                                                  'PolicyName': [policy['PolicyName']],
                                                  'PolicyType': [policy['PolicyType']],
                                                  'PolicyArn': [policy.get('PolicyArn', '')],
                                                  'EntityType': [policy.get('EntityType', '')],
                                                  'EntityName': [policy.get('EntityName', '')]})], ignore_index=True)
        if 'Marker' in response and response['IsTruncated']:
            marker = response['Marker']
        else:
            break


df.to_excel('data.xlsx', index=False)





